platform :ios, '11.0'

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_root = File.expand_path('..', File.dirname(`which flutter`))
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'Flutter', :path => File.join(flutter_application_path, 'flutter')

end
