export 'package:get/get.dart';
export 'package:get_it/get_it.dart';
export 'package:flutter/gestures.dart';
export 'package:flutter/material.dart';
export 'package:flutter/foundation.dart';
export 'package:dartz/dartz.dart' hide State;
export 'package:flutter_svg/flutter_svg.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:json_annotation/json_annotation.dart';
export 'package:syncfusion_flutter_charts/charts.dart';
export 'package:pretty_dio_logger/pretty_dio_logger.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:smooth_page_indicator/smooth_page_indicator.dart';
export 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';

///firebase_options file
export '/firebase_options.dart';

///routes file
export '/routes/routes.dart';
export '/routes/route_generator.dart';

///config file

export '/config/all_imports.dart';
export '/config/constants/api_keys.dart';
export '/config/dependency_injection.dart';
export '/config/constants/app_constants.dart';
export '/config/constants/api_constants.dart';
export '/config/constants/locale_constants.dart';

///core file

export '/core/language/ar.dart';
export '/core/language/en.dart';
export '/core/util/size_util.dart';
export '/core/validator/validator.dart';
export '/core/widgets/menu_Button.dart';
export '/core/widgets/custom_table.dart';
export '/core/language/translation.dart';
export '/core/widgets/custom_toast.dart';
export '/core/widgets/custom_button.dart';
export '/core/extensions/extensions.dart';
export '/core/service/theme_service.dart';
export '/core/widgets/custom_drawer.dart';
export '/core/widgets/custom_spacing.dart';
export '/core/helper/function_helper.dart';
export '/core/use_case/base_use_case.dart';
export '/core/resource/manager_sizes.dart';
export '/core/resource/manager_fonts.dart';
export '/core/widgets/custom_loading.dart';
export '/core/networking/api/app_api.dart';
export '/core/resource/manager_assets.dart';
export '/core/resource/manager_colors.dart';
export '/core/widgets/custom_pop_scope.dart';
export '/core/theme/manager_dark_theme.dart';
export '/core/resource/manager_strings.dart';
export '/core/theme/manager_light_theme.dart';
export '/core/helper/format_name_helper.dart';
export '/core/widgets/custom_text_field.dart';
export '/core/networking/api/dio_factory.dart';
export '/core/resource/manager_text_theme.dart';
export '/core/error_handler/response_code.dart';
export '/core/error_handler/error_handler.dart';
export '/core/middleware/route_middleware.dart';
export '/core/resource/manager_text_styles.dart';
export '/core/widgets/custom_head_of_official_paper.dart';
export '/core/resource/manager_text_theme_dark.dart';
export '/core/resource/manager_text_theme_light.dart';
export '/core/internet_checker/internet_checker.dart';
export '/core/widgets/confirm_information_dialog.dart';
export '/core/helper/format_date_and_time_helper.dart';
export '/config/constants/shared_preferences_keys.dart';
export '/core/widgets/custom_cached_network_image.dart';
export '/core/widgets/custom_back_driving_license_card.dart';
export '/core/widgets/custom_front_driving_license_card.dart';
export '/core/widgets/custom_created_successfully_dialog.dart';
export '/core/networking/firebase/firebase_notifications/fb_notifications.dart';
export '/core/storage/local/shared_preferences/shared_preferences_controller.dart';

///features file
//on_boarding feature
export '/features/on_boarding/presentation/view/widgets/move_button.dart';
export '/features/on_boarding/presentation/view/widgets/page_view_content.dart';
export '/features/on_boarding/presentation/view/screens/on_boarding_screen.dart';
export '/features/on_boarding/presentation/controller/on_boarding_controller.dart';

//login feature
export '/features/login/data/mapper/police_man_mapper.dart';
export '/features/login/data/mapper/driver_login_mapper.dart';
export '/features/login/domain/model/driver_login_model.dart';
export '/features/login/data/request/driver_login_request.dart';
export '../core/widgets/custom_rich_text.dart';
export '/features/login/domain/model/police_man_login_model.dart';
export '../core/widgets/custom_check_box.dart';
export '/features/login/data/response/driver_login_response.dart';
export '/features/login/domain/use_case/driver_login_use_case.dart';
export '/features/login/data/request/police_man_login_request.dart';
export '/features/login/presentation/view/screens/login_screen.dart';
export '/features/login/presentation/view/widgets/custom_tab_bar_page.dart';
export '/features/login/data/response/police_man_login_response.dart';
export '/features/login/presentation/view/screens/welcome_screen.dart';
export '/features/login/presentation/view/widgets/custom_tab_bar_button.dart';
export '/features/login/presentation/controller/login_controller.dart';
export '/features/login/domain/repository/driver_login_repository.dart';
export '/features/login/domain/use_case/police_man_login_use_case.dart';
export '/features/login/presentation/controller/welcome_controller.dart';
export '/features/login/domain/repository/police_man_login_repository.dart';
export '/features/login/data/data_source/remote_driver_login_data_source.dart';
export '/features/login/data/data_source/remote_police_man_login_data_source.dart';
export '/features/login/data/repository_impl/police_man_login_repository_impl.dart';
export '/features/login/data/repository_impl/driver_login_repository_implementation.dart';

//home feature

export '/features/home/domain/repo/home_driver_repo.dart';
export '/features/home/domain/repo/home_police_man_repo.dart';
export '/features/home/domain/model/home_police_man_model.dart';
export '/features/home/data/mapper/home_police_man_mapper.dart';
export '/features/home/domain/model/update_fcm_token_model.dart';
export '/features/home/data/mapper/update_fcm_token_mapper.dart';
export '/features/home/data/repo_impl/home_driver_repo_impl.dart';
export '/features/home/data/request/update_fcm_token_request.dart';
export '/features/home/data/response/home_police_man_response.dart';
export '/features/home/data/response/update_fcm_token_response.dart';
export '/features/home/data/repo_impl/home_police_man_repo_impl.dart';
export '/features/home/domain/use_case/home_police_man_use_case.dart';
export '/features/home/domain/use_case/update_fcm_token_use_case.dart';
export '/features/home/presentation/view/screens/driver_home_screen.dart';
export '/features/home/presentation/view/widgets/custom_home_app_bar.dart';
export '/features/home/presentation/controller/driver_home_controller.dart';
export '/features/home/presentation/view/widgets/custom_page_view_item.dart';
export '/features/home/data/data_source/remote_home_driver_data_source.dart';
export '/features/home/presentation/view/screens/police_man_home_screen.dart';
export '/features/home/presentation/controller/police_man_home_controller.dart';
export '/features/home/data/data_source/remote_home_police_man_data_source.dart';
export '/features/home/presentation/view/widgets/custom_bar_chart_distribution.dart';
export '/features/home/presentation/view/widgets/custom_statistics_box_of_police_man.dart';
export '/features/home/presentation/view/widgets/custom_box_of_number_of_violation_driver.dart';
export '/features/home/presentation/view/widgets/custom_button_for_violation_distribution_pages.dart';

//violation feature
export '/features/violation/data/mapper/all_violation_mapper.dart';
export '/features/violation/domain/model/all_violation_model.dart';
export '/features/violation/data/request/all_violation_request.dart';
export '/features/violation/domain/model/create_violation_model.dart';
export '/features/violation/data/mapper/create_violation_mapper.dart';
export '/features/violation/data/response/all_violation_response.dart';
export '/features/violation/data/request/create_violation_request.dart';
export '/features/violation/domain/use_case/all_violation_use_case.dart';
export '/features/violation/domain/repository/violation_repository.dart';
export '/features/violation/data/response/create_violation_response.dart';
export '/features/violation/data/mapper/get_violation_details_mapper.dart';
export '/features/violation/domain/model/get_violation_details_model.dart';
export '/features/violation/domain/use_case/create_violation_use_case.dart';
export '/features/notifications/data/request/save_notification_request.dart';
export '/features/violation/domain/use_case/save_notification_use_case.dart';
export '/features/violation/data/request/get_violation_details_request.dart';
export '/features/violation/data/mapper/all_reasons_of_violation_mapper.dart';
export '/features/violation/domain/model/all_reasons_of_violation_model.dart';
export '/features/violation/data/response/get_violation_details_response.dart';
export '/features/violation/data/data_source/remote_violation_data_source.dart';
export '/features/violation/domain/use_case/get_violation_details_use_case.dart';
export '/features/violation/domain/repository/save_notification_repository.dart';
export '/features/violation/data/repository_impl/violation_repository_impl.dart';
export '/features/violation/data/response/all_reasons_of_violation_response.dart';
export '/features/violation/presentation/view/widgets/custom_search_drop_down.dart';
export '/features/violation/presentation/view/screens/create_violation_screen.dart';
export '/features/violation/domain/use_case/all_reasons_of_violation_use_case.dart';
export '/features/violation/presentation/view/widgets/custom_violation_details.dart';
export '/features/violation/presentation/controller/create_violation_controller.dart';
export '/features/violation/presentation/view/screens/list_of_violations_screen.dart';
export '/features/violation/data/data_source/remote_save_notification_data_source.dart';
export '/features/violation/presentation/controller/list_of_violations_controller.dart';
export '/features/violation/data/repository_impl/save_notification_repository_impl.dart';
export '/features/violation/presentation/view/widgets/custom_item_card_of_list_of_violation.dart';

//search feature
export '/features/search/data/mapper/search_for_driver_mapper.dart';
export '/features/search/domain/model/search_for_driver_model.dart';
export '/features/search/data/request/search_for_driver_request.dart';
export '/features/search/presentation/view/widgets/row_of_table.dart';
export '/features/search/data/response/search_for_driver_response.dart';
export '/features/search/domain/use_case/search_for_driver_use_case.dart';
export '/features/search/presentation/view/widgets/result_of_driver.dart';
export '/features/search/presentation/view/widgets/result_of_license.dart';
export '/features/search/presentation/view/widgets/border_side_of_table.dart';
export '/features/search/domain/repository/search_for_driver_repository.dart';
export '/features/search/presentation/view/screens/search_for_driver_screen.dart';
export '/features/search/presentation/controller/search_for_driver_controller.dart';
export '/features/search/presentation/view/widgets/custom_empty_result_search.dart';
export '/features/search/presentation/view/widgets/custom_card_of_result_test.dart';
export '/features/search/data/mapper/search_on_results_tests_of_license_mapper.dart';
export '/features/search/data/data_source/remote_search_for_driver_data_source.dart';
export '/features/search/domain/model/search_on_results_tests_of_license_model.dart';
export '/features/search/data/repository_impl/search_for_driver_repository_impl.dart';
export '/features/search/data/request/search_on_results_tests_of_license_request.dart';
export '/features/search/presentation/view/widgets/custom_template_search_screen.dart';
export '/features/search/data/response/search_on_results_tests_of_license_response.dart';
export '/features/search/domain/use_case/search_on_results_tests_of_license_use_case.dart';
export '/features/search/data/data_source/remote_search_on_tests_of_license_data_source.dart';
export '/features/search/domain/repository/search_on_results_tests_of_license_repository.dart';
export '/features/search/presentation/view/screens/search_on_results_tests_of_license_screen.dart';
export '/features/search/presentation/controller/search_on_results_tests_of_license_controller.dart';
export '/features/search/data/repository_impl/search_on_results_test_of_license_repository_impl.dart';

//logout feature
export '/features/logout/presentation/view/screens/logout_screen.dart';
export '/features/logout/presentation/controller/logout_controller.dart';

//driving_license_card feature
export '/features/driving_license_card/presentation/view/widgets/custom_expansion_tile_card.dart';
export '/features/driving_license_card/presentation/view/screens/driving_license_card_screen.dart';
export '/features/driving_license_card/presentation/controller/driving_license_card_controller.dart';

//complaints feature
export '/features/complaints/domain/model/create_complaint_model.dart';
export '/features/complaints/data/mapper/create_complaint_mapper.dart';
export '/features/complaints/domain/model/get_all_complaints_model.dart';
export '/features/complaints/data/request/create_complaint_request.dart';
export '/features/complaints/data/mapper/get_all_complaints_mapper.dart';
export '/features/complaints/data/response/create_complaint_response.dart';
export '/features/complaints/data/request/get_all_complaints_request.dart';
export '/features/complaints/domain/use_case/create_complaint_use_case.dart';
export '/features/complaints/domain/use_case/get_all_complaints_use_case.dart';
export '/features/complaints/domain/repository/create_complaint_repository.dart';
export '/features/complaints/presentation/view/widgets/custom_field_of_row.dart';
export '/features/complaints/domain/repository/get_all_complaints_repository.dart';
export '/features/complaints/presentation/view/screens/list_of_complaints_screen.dart';
export '/features/complaints/presentation/view/widgets/dialog_of_create_complaint.dart';
export '/features/complaints/data/response/get_all_complaints_for_driver_response.dart';
export '/features/complaints/data/data_source/remote_create_complaint_data_source.dart';
export '/features/complaints/presentation/controller/create_complaints_controller.dart';
export '/features/complaints/presentation/controller/list_of_complaints_controller.dart';
export '/features/complaints/data/repository_impl/create_complaint_repository_impl.dart';
export '/features/complaints/data/data_source/remote_get_all_complaints_data_source.dart';
export '/features/complaints/data/repository_impl/get_all_complaints_repository_impl.dart';
export '/features/complaints/presentation/view/widgets/custom_title_and_create_complaint.dart';

//change_password feature
export '/features/change_password/data/mapper/driver_change_password_mapper.dart';
export '/features/change_password/domain/model/driver_change_password_model.dart';
export '/features/change_password/data/request/driver_change_password_request.dart';
export '/features/change_password/data/mapper/police_man_change_password_mapper.dart';
export '/features/change_password/data/response/driver_change_password_response.dart';
export '/features/change_password/domain/model/police_man_change_password_model.dart';
export '/features/change_password/domain/use_case/driver_change_password_use_case.dart';
export '/features/change_password/data/request/police_man_change_password_request.dart';
export '/features/change_password/presentation/view/screens/change_password_screen.dart';
export '/features/change_password/data/response/police_man_change_password_response.dart';
export '/features/change_password/presentation/controller/change_password_controller.dart';
export '/features/change_password/domain/repository/driver_change_password_repository.dart';
export '/features/change_password/domain/use_case/police_man_change_password_use_case.dart';
export '/features/change_password/domain/repository/police_man_change_password_repository.dart';
export '/features/change_password/data/data_source/remote_driver_change_password_data_source.dart';
export '/features/change_password/data/repository_impl/driver_change_password_repository_impl.dart';
export '/features/change_password/data/data_source/remote_police_man_change_password_data_source.dart';
export '/features/change_password/data/repository_impl/police_man_change_password_repository_impl.dart';

//forget_password feature
export '/features/forget_password/data/request/verify_code_sent_request.dart';
export '/core/networking/firebase/firebase_authentication/fb_authentication.dart';
export '/features/forget_password/data/response/verify_code_sent_response.dart';
export '/features/forget_password/domain/model/send_verification_code_model.dart';
export '/features/forget_password/data/mapper/driver_forgot_password_mapper.dart';
export '/features/forget_password/domain/model/driver_forgot_password_model.dart';
export '/features/forget_password/data/mapper/send_verification_code_mapper.dart';
export '/features/forget_password/data/request/send_verification_code_request.dart';
export '/features/forget_password/data/request/driver_forgot_password_request.dart';
export '/features/forget_password/data/response/send_verification_code_response.dart';
export '/features/forget_password/data/mapper/police_man_forgot_password_mapper.dart';
export '/features/forget_password/data/response/driver_forgot_password_response.dart';
export '/features/forget_password/domain/model/police_man_forgot_password_model.dart';
export '/features/forget_password/domain/use_case/send_verification_code_use_case.dart';
export '/features/forget_password/domain/use_case/driver_forgot_password_use_case.dart';
export '/features/forget_password/data/request/police_man_forgot_password_request.dart';
export '/features/forget_password/presentation/view/screens/forgot_password_screen.dart';
export '/features/forget_password/data/response/police_man_forgot_password_response.dart';
export '/features/forget_password/presentation/controller/forgot_password_controller.dart';
export '/features/forget_password/presentation/view/screens/verification_code_screen.dart';
export '/features/forget_password/presentation/view/widgets/custom_verification_image.dart';
export '/features/forget_password/domain/use_case/police_man_forgot_password_use_case.dart';
export '/features/forget_password/domain/repository/driver_forgot_password_repository.dart';
export '/features/forget_password/domain/repository/send_verification_code_repository.dart';
export '/features/forget_password/presentation/controller/verification_code_controller.dart';
export '/features/forget_password/domain/repository/police_man_forgot_password_repository.dart';
export '/features/forget_password/data/data_source/remote_driver_forgot_password_data_source.dart';
export '/features/forget_password/data/data_source/remote_send_verification_code_data_source.dart';
export '/features/forget_password/presentation/view/widgets/custom_filed_of_verification_code.dart';
export '/features/forget_password/data/repository_impl/driver_forgot_password_repository_impl.dart';
export '/features/forget_password/data/data_source/remote_police_man_forgot_password_data_source.dart';
export '/features/forget_password/data/repository_impl/police_man_forgot_password_repository_impl.dart';
export '/features/forget_password/presentation/view/widgets/custom_incorrect_entered_code_message.dart';

//profile feature
export '/features/profile/presentation/view/widgets/custom_image_profile.dart';
export '/features/profile/domain/model/send_request_update_profile_model.dart';
export '/features/profile/data/mapper/send_request_update_profile_mapper.dart';
export '/features/profile/presentation/view/screens/driver_profile_screen.dart';
export '/features/profile/data/request/send_request_update_profile_request.dart';
export '/features/profile/presentation/controller/driver_profile_controller.dart';
export '/features/profile/data/response/send_request_update_profile_response.dart';
export '/features/profile/domain/use_case/send_request_update_profile_use_case.dart';
export '/features/profile/domain/repository/send_request_update_profile_repository.dart';
export '/features/profile/data/data_source/remote_send_request_update_profile_data_source.dart';
export '/features/profile/data/repository_impl/send_request_update_profile_repository_impl.dart';

//payment feature
export '/features/payment/data/mapper/driver_violations_mapper.dart';
export '/features/payment/domain/model/driver_violations_model.dart';
export '/features/payment/data/mapper/payment_violation_mapper.dart';
export '/features/payment/domain/model/payment_violation_model.dart';
export '/features/payment/data/request/driver_violations_request.dart';
export '/features/payment/data/request/payment_violation_request.dart';
export '/features/payment/presentation/view/widgets/custom_state_payment.dart';
export '/features/payment/data/response/driver_violations_response.dart';
export '/features/payment/data/response/payment_violation_response.dart';
export '/features/payment/presentation/view/screens/payment_screen.dart';
export '/features/payment/presentation/view/widgets/custom_payment_method.dart';
export '/features/payment/domain/model/driver_violations_data_model.dart';
export '/features/payment/domain/use_case/payment_violation_use_case.dart';
export '/features/payment/presentation/controller/payment_controller.dart';
export '/features/payment/domain/use_case/driver_violations_use_case.dart';
export '/features/payment/domain/repository/driver_violations_repository.dart';
export '/features/payment/domain/repository/payment_violation_repository.dart';
export '/features/payment/presentation/view/screens/driver_violations_screen.dart';
export '/features/payment/presentation/view/widgets/custom_enter_details_step.dart';
export '/features/payment/presentation/controller/driver_violations_controller.dart';
export '/features/payment/presentation/view/widgets/custom_table_of_violations.dart';
export '/features/payment/data/data_source/remote_driver_violations_data_source.dart';
export '/features/payment/data/data_source/remote_payment_violation_data_source.dart';
export '/features/payment/data/repository_impl/driver_violations_repository_impl.dart';
export '/features/payment/data/repository_impl/payment_violation_repository_impl.dart';
export '/features/payment/presentation/view/widgets/custom_payment_selection_step.dart';
export '/features/payment/presentation/view/widgets/custom_filter_violations_item.dart';
export '/features/payment/presentation/view/widgets/custom_view_violation_details.dart';
export '/features/payment/presentation/view/widgets/custom_filter_violations_button.dart';
export '/features/payment/presentation/view/widgets/custom_payment_confirmation_step.dart';

//notifications feature
export '/features/notifications/presentation/model/notification_model.dart';
export '/features/notifications/presentation/view/widgets/box_of_notification.dart';
export '/features/notifications/presentation/view/screens/notifications_screen.dart';
export '/features/notifications/presentation/controller/notifications_controller.dart';
