name: Flutter Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # تحديد إصدار Flutter

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios
          pod install --repo-update

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/ios/iphoneos/Runner.ipa  # تغيير المسار إلى .ipa
