name: Build iOS App

on:
  push:
    branches:
      - master  # سيتم تنفيذ الـ workflow عند الدفع إلى الفرع الرئيسي
  pull_request:
    branches:
      - master  # سيتم تنفيذ الـ workflow عند تقديم PR إلى الفرع الرئيسي

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Modify Podfile to set iOS version to 13.0
        run: |
          cd ios
          echo "platform :ios, '13.0'" >> Podfile

      - name: Build iOS without signing
        run: flutter build ios --no-codesign --release
