name: Build iOS App

on:
  push:
    branches:
      - master  # سيتم تنفيذ الـ workflow عند الدفع إلى الفرع الرئيسي
  pull_request:
    branches:
      - master  # سيتم تنفيذ الـ workflow عند تقديم PR إلى الفرع الرئيسي

jobs:
  build:
    runs-on: macos-latest  # يعمل على خوادم macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # تنزيل الكود من المستودع

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release
