name: Build iOS App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Check Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Modify Podfile
        run: |
          cd ios
          echo "platform :ios, '13.0'" > Podfile
          echo "flutter_application_path = '../'" >> Podfile
          echo "load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')" >> Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_frameworks!" >> Podfile
          echo "  use_modular_headers!" >> Podfile
          echo "  install_all_flutter_pods(flutter_application_path)" >> Podfile
          echo "end" >> Podfile
          echo "post_install do |installer|" >> Podfile
          echo "  flutter_post_install(installer)" >> Podfile
          echo "end" >> Podfile

      - name: Verify Podfile
        run: |
          cd ios
          cat Podfile

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.0
          pod setup

      - name: Clean iOS build and reinstall pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock Flutter/App.framework Flutter/Flutter.xcframework
          pod deintegrate
          flutter pub get
          pod install --repo-update

      - name: Build iOS without signing
        run: flutter build ios --no-codesign --release