name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter 3.24.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Enable iOS Platform
        run: flutter config --enable-ios #

      - name: Get Dependencies
        run: flutter pub get

      - name: Clean & Setup iOS
        run: |
          cd ios
          flutter clean
          pod install --verbose

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
