name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter 3.24.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Enable iOS Platform
        run: flutter config --enable-ios

      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios
          rm -rf Podfile.lock Pods
          rm -f Flutter/Generated.xcconfig
          flutter pub get

      - name: Create Podfile if not exists
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Creating Podfile..."
            echo "platform :ios, '11.0'" > ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  use_frameworks!" >> ios/Podfile
            echo "  pod 'FirebaseCore', '~> 11.6.0'" >> ios/Podfile
            echo "  pod 'FirebaseAuth', '~> 11.6.0'" >> ios/Podfile
            echo "  pod 'FirebaseMessaging', '~> 11.6.0'" >> ios/Podfile
            echo "  pod 'Flutter', :path => '../flutter'" >> ios/Podfile
            echo "end" >> ios/Podfile
          else
            echo "Podfile already exists"
          fi

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --project-directory=ios

      - name: Build iOS App (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
