name: Build iOS App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      - name: Check Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Update packages
        run: flutter pub upgrade

      - name: Clean Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer # Replace with your Xcode path

      - name: Modify Podfile
        run: |
          cd ios
          echo "platform :ios, '13.0'" > Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_frameworks! " >> Podfile
          echo "  use_modular_headers! " >> Podfile
          echo "  flutter_install_ios_pods File.dirname(File.realpath(__FILE__))" >> Podfile
          echo "end" >> Podfile

      - name: Verify Podfile
        run: |
          cd ios
          cat Podfile

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.0
          pod setup

      - name: Clean iOS build and reinstall pods
        run: |
          cd ios
          rm -rf build
          rm -rf Podfile.lock
          rm -rf Pods
          pod deintegrate
          flutter pub get
          pod install

      - name: Build iOS without signing
        run: flutter build ios --no-codesign --release