name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter 3.24.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Enable iOS Platform
        run: flutter config --enable-ios

      - name: Set Xcode Version (13.0)
        run: |
          sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Get Dependencies
        run: |
          flutter pub get
          flutter doctor -v # Ensure no issues with dependencies

      - name: Clean Flutter Project
        run: flutter clean

      - name: Clean & Setup iOS
        run: |
          cd ios
          flutter pub get # Ensure dependencies are fetched for iOS
          pod install --verbose || pod update # Try installing pods or updating them if necessary

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/*.app # Ensure you upload the correct artifact (iOS app package)
