name: Build Flutter iOS App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-ios:
    runs-on: macos-latest  # Use a macOS runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Use the stable Flutter channel

      # Install CocoaPods dependencies
      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install
        working-directory: ./ios

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Generate code for Retrofit, JSON serialization, etc.
      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Build the iOS app
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      # Optional: Archive the iOS app (requires a development team and provisioning profile)
      # - name: Archive iOS app
      #   run: |
      #     cd ios
      #     xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath RunnerArchive
      #   env:
      #     DEVELOPER_TEAM: YOUR_DEVELOPER_TEAM_ID
      #     PROVISIONING_PROFILE_SPECIFIER: YOUR_PROVISIONING_PROFILE

      # Optional: Export the .ipa file (requires a development team and provisioning profile)
      # - name: Export .ipa
      #   run: |
      #     xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist
      #   env:
      #     DEVELOPER_TEAM: YOUR_DEVELOPER_TEAM_ID
      #     PROVISIONING_PROFILE_SPECIFIER: YOUR_PROVISIONING_PROFILE

      # Upload the .ipa file as an artifact (using v4 of upload-artifact)
      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: build/ios/ipa/Runner.ipa