name: Build iOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Check Flutter doctor
        run: flutter doctor -v

      - name: Set iOS platform version
        run: |
          cd ios
          echo "platform :ios, '13.0'" >> Podfile

      - name: Clean Flutter project
        run: flutter clean

      - name: Clean iOS build and reinstall pods
        run: |
          cd ios
          rm -rf build
          rm -rf Podfile.lock
          rm -rf Pods
          pod deintegrate
          flutter pub get # run flutter pub get before pod install
          pod install

      - name: Build iOS without signing
        run: flutter build ios --no-codesign --release
